### ISSUE TITLE
enable atom feed for your site

### ISSUE THREAD

**Issue by ahmedre** [vourkosa/vourkosa.github.io#1]
hi,
i like the post about `addContentView` - was hoping i could follow the rss/atom feed, but there isn't one. i looked and saw that if you were to add:

```
gems:
  - jekyll-feed
```

to `_config.yml`, that it should add an atom feed (according to [github help](https://help.github.com/articles/atom-rss-feeds-for-github-pages/)).

i would submit a pull request, but not really sure how to test this so don't want to submit a broken pull request - thanks!

**Comment by kaspanvo** [comment]
Hello Ahmed

Thank you for your email. I am glad that you liked the article.

I added rss/atom support as suggested. You can find it now here:
http://vourkosa.github.io/feed.xml

Kind Regards

**Comment by ahmedre** [comment]
thanks!
